Países= ['Portugal','EUA','Dubai','Brasil', 'Japão','França','China']
print('Ordem original da lista : ',Países)
print()
print("Está é a ordem da lista organizada temporariamente em ordem alfabética: ",sorted(Países))
print()
print("Está é a ordem original da lista de novo: ",Países)
print()
print(sorted(Países, reverse=True))
print()
print("Ordem original ", Países)
Países.reverse()
print()
print(Países)
print()
Países.reverse()
print(Países)
print()
Países.sort()
print(Países)
print()
Países.sort(reverse=True)
print(Países)